### ISSUE TITLE
Cursor disappears after using Select

### ISSUE THREAD

**Issue by francisdb** [console-rs/dialoguer#283] opened 2023-09-27 10:12 UTC
dialoguer = "0.11.0"

After showing a select to the user and exiting the application the cursor is no longer visible. I have to do a console `reset` to fix this.

I think this was introduced in latest release. 

```rust
Select::with_theme(&ColorfulTheme::default())
            .with_prompt("Select a table to launch")
            .default(selection_opt.unwrap_or(0))
            .items(&selections[..])
            .interact_opt()
            .unwrap();
```

**Comment by pksunkara** [comment] 2023-09-27 12:01
Duplicate of #188

**Closed by pksunkara** 2023-09-27 12:01 UTC
